-- PDBへ切り替え
ALTER SESSION SET CONTAINER=pdb01;

-- ユーザ作成
CREATE USER atman IDENTIFIED BY atman
DEFAULT TABLESPACE users
QUOTA UNLIMITED ON users
TEMPORARY TABLESPACE temp;
GRANT CONNECT, RESOURCE TO atman;
ALTER USER atman QUOTA UNLIMITED ON users;

-- パスワードを無期限に変更
ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;

-- 作成ユーザへ権限付与
GRANT CREATE SESSION TO atman;
GRANT RESOURCE TO atman;
GRANT UNLIMITED TABLESPACE TO atman;